environments:
  default:
    values:
      - "envs/local.yaml"
---
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
releases:
  - name: kafka
    chart: bitnami/kafka
    installed: false
    values:
      - values/kafka.values.yaml.gotmpl
